export const initialState = {
  products: {
    data: [
      // {
      //   _id: '55558',
      //   color: '#f7d258',
      //   number: '13-0755',
      //   name: 'Primrose Yellow',
      //   price: 25,
      // },
      // {
      //   _id: '44458',
      //   color: '#f0cfc6',
      //   number: '13-1404',
      //   name: 'Pale Dogwood',
      //   price: 26,
      // },
      // {
      //   id: 2,
      //   color: '#d1af94',
      //   number: '14-1315',
      //   name: 'Hazelnut',
      //   price: 24,
      // },
      // {
      //   id: 3,
      //   color: '#98d3de',
      //   number: '14-4620',
      //   name: 'Island Paradise',
      //   price: 23,
      // },
      // {
      //   id: 4,
      //   color: '#88b14a',
      //   number: '15-0343',
      //   name: 'Greenery',
      //   price: 22,
      // },
      // {
      //   id: 5,
      //   color: '#ea5730',
      //   number: '17-1462',
      //   name: 'Flame',
      //   price: 24,
      // },
      // {
      //   id: 6,
      //   color: '#d23076',
      //   number: '717-2034',
      //   name: 'Pink Yarrow',
      //   price: 25,
      // },
      // {
      //   id: 7,
      //   color: '#c9b199',
      //   number: '711-2331',
      //   name: 'sand',
      //   price: 25,
      // },
      // {
      //   id: 8,
      //   color: '#5687a2',
      //   number: '17-4123',
      //   name: 'Nieagar',
      //   price: 27,
      // },
      // {
      //   id: 9,
      //   color: '#5d7248',
      //   number: '18-0107',
      //   name: 'Kale',
      //   price: 26,
      // },
      // {
      //   id: 10,
      //   color: '#0d4c8b',
      //   number: '19-4045',
      //   name: 'Lapis Blue',
      //   price: 26,
      // },
      // {
      //   id: 11,
      //   color: '#ee766c',
      //   number: '16-1548',
      //   name: 'Peach Echo',
      //   price: 28,
      // },
      // {
      //   id: 12,
      //   color: '#f8df3d',
      //   number: '12-0752',
      //   name: 'Buttercup',
      //   price: 29,
      // },
      // {
      //   id: 13,
      //   color: '#d086a3',
      //   number: '16-2215',
      //   name: 'Cashmere Rose',
      //   price: 24,
      // },
      // {
      //   id: 14,
      //   color: '#044f83',
      //   number: '19-4049',
      //   name: 'Snorkel Blue',
      //   price: 25,
      // },
      // {
      //   id: 15,
      //   color: '#9996a4',
      //   number: '16-3905',
      //   name: 'Lilac Gray',
      //   price: 21,
      // },
      // {
      //   id: 16,
      //   color: '#ccd620',
      //   number: '13-0650',
      //   name: 'Sulphur Spring',
      //   price: 22,
      // },
      // {
      //   id: 17,
      //   color: '#eb5983',
      //   number: '16-1735',
      //   name: 'Pink Lemonade',
      //   price: 22,
      // },
    ],
  },
  cart: [],
};
