export const initialState = {
  products: {
    data: [
      {
        id: 0,
        color: '#f7d258',
        number: '13-0755',
        name: 'Primrose Yellow',
      },
      {
        id: 1,
        color: '#f0cfc6',
        number: '13-1404',
        name: 'Pale Dogwood',
      },
      {
        id: 2,
        color: '#d1af94',
        number: '14-1315',
        name: 'Hazelnut',
      },
      {
        id: 3,
        color: '#98d3de',
        number: '14-4620',
        name: 'Island Paradise',
      },
      {
        id: 4,
        color: '#88b14a',
        number: '15-0343',
        name: 'Greenery',
      },
      {
        id: 5,
        color: '#ea5730',
        number: '17-1462',
        name: 'Flame',
      },
      {
        id: 6,
        color: '#d23076',
        number: '717-2034',
        name: 'Pink Yarrow',
      },
      {
        id: 7,
        color: 'grey',
        number: '711-2331',
        name: 'sand',
      },
      {
        id: 8,
        color: '#5687a2',
        number: '17-4123',
        name: 'Nieagar',
      },
      {
        id: 9,
        color: '#5d7248',
        number: '18-0107',
        name: 'Kale',
      },
      {
        id: 10,
        color: '#0d4c8b',
        number: '19-4045',
        name: 'Lapis Blue',
      },
      {
        id: 11,
        color: '#ee766c',
        number: '16-1548',
        name: 'Peach Echo',
      },
      {
        id: 12,
        color: '#f8df3d',
        number: '12-0752',
        name: 'Buttercup',
      },
      {
        id: 13,
        color: '#d086a3',
        number: '16-2215',
        name: 'Cashmere Rose',
      },
      {
        id: 14,
        color: '#044f83',
        number: '19-4049',
        name: 'Snorkel Blue',
      },
      {
        id: 15,
        color: '#9996a4',
        number: '16-3905',
        name: 'Lilac Gray',
      },
      {
        id: 16,
        color: '#ccd620',
        number: '13-0650',
        name: 'Sulphur Spring',
      },
      {
        id: 17,
        color: '#eb5983',
        number: '16-1735',
        name: 'Pink Lemonade',
      },
    ],
  },
  cart: [],
};
